---
packages:
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  standard_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_standard.yaml
  addon_media_player: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_addon_media_player.yaml

esp32:
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
...
