---
packages:
  core_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml
  standard_hw_speaker_package: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_standard_hw_speaker.yaml

esp32:
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
...
