####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Standard (non-essential, but recommended packages)                      #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################
---
packages:
  # yamllint disable rule:colons
  standard_hw_relays:    !include TX-Ultimate-Easy-ESPHome_standard_hw_relays.yaml
  standard_hw_vibration: !include TX-Ultimate-Easy-ESPHome_standard_hw_vibration.yaml
  standard_media_player: !include TX-Ultimate-Easy-ESPHome_standard_media_player.yaml
  # yamllint enable rule:colons

button:
  - id: bt_restart
    name: Restart
    internal: false
    platform: restart

esphome:
  platformio_options:
    build_flags:
      - -D TX_ULTIMATE_EASY_STANDARD

script:
  - id: !extend dump_config_list_packages
    then:
      - script.wait: dump_config
      - lambda: |-
          // Check for requirements
          #if !defined(TX_ULTIMATE_EASY_CORE)
            #error "The package TX-Ultimate-Easy-ESPHome_core.yaml is required."
          #endif

          // Identify itself
          ESP_LOGCONFIG(ESPHOME_PROJECT_NAME, "  - Standard");

  - id: !extend dump_config_versions
    then:
      - lambda: |-
          // Version information
          ESP_LOGCONFIG("standard", "ESPHome builder: %s", esphome_fw_version->state.c_str());
...
