####################################################################################################
#####                              TX Ultimate Easy for ESPHome                                #####
#####                  Repository: https://github.com/edwardtfn/TX-Ultimate-Easy               #####
####################################################################################################
##### Purpose: ESPHome Core - Hardware - Speaker                                               #####
####################################################################################################
##### Author: edwardtfn - https://github.com/edwardtfn - https://buymeacoffee.com/edwardfirmo  #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################
---
i2s_audio:
  id: if_i2s_audio
  i2s_bclk_pin: GPIO2
  i2s_lrclk_pin: GPIO4

media_player:
  - id: mp_speaker
    name: Speaker
    internal: false
    platform: i2s_audio
    i2s_dout_pin: GPIO15
    i2s_audio_id: if_i2s_audio
    i2s_comm_fmt: lsb
    dac_type: external
    mode: mono
...
