# This GitHub Actions workflow updates the "stable" and "latest" Git tags
# to point to the latest commit on the main branch whenever code is merged.
# It performs the following steps:
# 1. Checks out the repository code with full history
# 2. Configures Git with a generic user for the action
# 3. Moves and forcibly pushes the "stable" and "latest" tags to align with
#    the latest main branch commit
---
name: Update Tags

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  update-tags:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Move and push tags
        run: |
          echo "Creating/updating stable and latest tags pointing to latest main commit"
          git tag -fa stable -m "Update stable tag to latest main"
          git tag -fa latest -m "Update latest tag to latest main"
          git push origin stable latest --force
...
