---
name: Validate ESPHome (Latest)

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code_scan:
    name: Code scan (YAML)
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.8'

      - name: Install Yamllint
        run: pip install yamllint

      - name: Validate YAML files
        run: find . -name "*.yaml" -exec yamllint -c ./.rules/yamllint.yml {} +

  build_basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build core
        uses: esphome/build-action@main
        with:
          yaml-file: ".test/esphome_ard_basic.yaml"
          version: latest

  build_bluetooth_proxy_4:
    name: Bluetooth Proxy (IDF)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build core
        uses: esphome/build-action@main
        with:
          yaml-file: ".test/esphome_idf_bluetooth_proxy.yaml"
          version: latest

  build_bluetooth_proxy_53:
    name: Bluetooth Proxy (IDF v5.3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build core
        uses: esphome/build-action@main
        with:
          yaml-file: ".test/esphome_idf53_bluetooth_proxy.yaml"
          version: latest
...
